#! /bin/sh
#
# Created by configure

LDFLAGS="-L/usr/lib64"; export LDFLAGS
"./configure" \
"--with-pcre=/usr" \
"--with-ldap=yes" \
"--with-lap-include=/usr/include" \
"--with-ldap-lib=/usr/lib" \
"--enable-ssl" \
"--with-ssl=/usr/lib/ssl" \
"--enable-mpms-shared=all" \
"--enable-unixd=static" \
"--enable-layout=Debian" \
"--enable-so" \
"--with-program-name=apache2" \
"--with-suexec-caller=www-data" \
"--with-suexec-bin=/usr/lib/apache2/suexec" \
"--with-suexec-docroot=/var/www" \
"--with-suexec-userdir=public_html" \
"--with-suexec-logfile=/var/log/apache2/suexec.log" \
"--with-suexec-uidmin=100" \
"--enable-suexec=shared" \
"--enable-log-config=static" \
"--enable-logio=static" \
"--enable-version=static" \
"--with-apr=/usr/bin/apr-1-config" \
"--with-apr-util=/usr/bin/apu-1-config" \
"--with-pcre=yes" \
"--enable-pie" \
"--enable-authn-alias=shared" \
"--enable-disk-cache=shared" \
"--enable-cache=shared" \
"--enable-mem-cache=shared" \
"--enable-file-cache=shared" \
"--enable-cern-meta=shared" \
"--enable-dumpio=shared" \
"--enable-ext-filter=shared" \
"--enable-charset-lite=shared" \
"--enable-cgi=shared" \
"--enable-dav-lock=shared" \
"--enable-log-forensic=shared" \
"--enable-proxy=shared" \
"--enable-proxy-connect=shared" \
"--enable-proxy-ftp=shared" \
"--enable-proxy-http=shared" \
"--enable-proxy-ajp=shared" \
"--enable-proxy-scgi=shared" \
"--enable-proxy-balancer=shared" \
"--enable-ssl=shared" \
"--enable-authn-dbm=shared" \
"--enable-authn-anon=shared" \
"--enable-authn-dbd=shared" \
"--enable-authn-file=shared" \
"--enable-authn-default=shared" \
"--enable-authz-host=shared" \
"--enable-authz-groupfile=shared" \
"--enable-authz-user=shared" \
"--enable-authz-dbm=shared" \
"--enable-authz-owner=shared" \
"--enable-authz-default=shared" \
"--enable-auth-basic=shared" \
"--enable-auth-digest=shared" \
"--enable-dbd=shared" \
"--enable-deflate=shared" \
"--enable-include=shared" \
"--enable-filter=shared" \
"--enable-env=shared" \
"--enable-mime-magic=shared" \
"--enable-expires=shared" \
"--enable-headers=shared" \
"--enable-ident=shared" \
"--enable-usertrack=shared" \
"--enable-unique-id=shared" \
"--enable-setenvif=shared" \
"--enable-status=shared" \
"--enable-autoindex=shared" \
"--enable-asis=shared" \
"--enable-info=shared" \
"--enable-cgid=shared" \
"--enable-dav=shared" \
"--enable-dav-fs=shared" \
"--enable-vhost-alias=shared" \
"--enable-negotiation=shared" \
"--enable-dir=shared" \
"--enable-imagemap=shared" \
"--enable-actions=shared" \
"--enable-speling=shared" \
"--enable-userdir=shared" \
"--enable-alias=shared" \
"--enable-rewrite=shared" \
"--enable-mime=shared" \
"--enable-substitute=shared" \
"--enable-reqtimeout=shared" \
"LDFLAGS=-L/usr/local/lib" \
"$@"
